[package]
name = "tmc-langs-util"
version = "0.1.0"
authors = ["University of Helsinki <mooc@cs.helsinki.fi>", "Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
tmc-langs-framework = { path = "../tmc-langs-framework" }
tmc-langs-csharp = { path = "../plugins/csharp" }
tmc-langs-java = { path = "../plugins/java" }
tmc-langs-make = { path = "../plugins/make" }
tmc-langs-notests = { path = "../plugins/notests" }
tmc-langs-python3 = { path = "../plugins/python3" }
tmc-langs-r = { path = "../plugins/r" }

heim = { version = "0.1.0-beta.3", features = ["disk"] }
impl-enum = "0.2"
lazy_static = "1"
log = "0.4"
md5 = "0.7"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
schemars = "0.8"
shellwords = "1"
smol = "1"
tar = "0.4"
tempfile = "3"
thiserror = "1"
type-map = "0.4"
walkdir = "2"
zip = "0.5"
zstd = "0.6"

[target.'cfg(unix)'.dependencies]
nix = "0.19"

[dev-dependencies]
simple_logger = "1"
