[package]
name = "tmc-langs-framework"
version = "0.1.0"
authors = ["University of Helsinki <mooc@cs.helsinki.fi>", "Daniel Martinez <daniel.x.martinez@helsinki.fi>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
tmc-langs-util = { path = "../tmc-langs-util" }

anyhow = "1"
fd-lock = "2"
funty = "=1.1.0"  # temporary workaround, remove later
isolang = "1"
lazy_static = "1"
log = "0.4"
nom = { version = "6", features = ["alloc"] }
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
schemars = "0.8"
subprocess = "0.2"
tempfile = "3"
thiserror = "1"
walkdir = "2"
zip = "0.5"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"

[dev-dependencies]
mockall = "0.9"
simple_logger = "1"
tempfile = "3"
